const fs=require('fs');
const path='data/titles.json';
const data=JSON.parse(fs.readFileSync(path,'utf8'));
const editorial=id=>({kind:'editorial',source:'Musical Propulsion Engine analysis',titleId:id});
const P={
  jamie:{format:'film',musicalType:'adaptation',vocalStyle:['Pop-musical','Bright belt','Ensemble'],lyricalDensity:4,musicDrivenPercent:72,catharsis:4.5,rewatchability:4.4,familiarityAdvantage:2,bestMood:['Defiant','Celebratory','Needs a lift'],friction:['Coming-of-age framing may feel lighter than the emotional themes underneath'],gatewaySongs:[{song:"Don't Even Know It",purpose:'instant propulsion test'},{song:'The Wall in My Head',purpose:'emotional depth test'},{song:'Out of the Darkness',purpose:'catharsis test'}],notes:'A buoyant pop-musical with real emotional stakes, strongest when self-definition becomes anthem.',provenance:[editorial('jamie')]},
  hedwig:{format:'film',musicalType:'adaptation',vocalStyle:['Glam rock','Rock belt','Character-driven'],lyricalDensity:4,musicDrivenPercent:78,catharsis:4.8,rewatchability:4.2,familiarityAdvantage:2,bestMood:['Want weird','Rock mood','Identity catharsis'],friction:['Angular tone and deliberately abrasive character work'],gatewaySongs:[{song:'Wig in a Box',purpose:'hook and identity test'},{song:'The Origin of Love',purpose:'mythic emotional test'},{song:'Midnight Radio',purpose:'catharsis test'}],notes:'Cult rock musical where identity, performance, and emotional rupture are fused into the songs.',provenance:[editorial('hedwig')]},
  dreamgirls:{format:'film',musicalType:'adaptation',vocalStyle:['Soul belt','R&B','Power vocal'],lyricalDensity:3.5,musicDrivenPercent:74,catharsis:5,rewatchability:4.1,familiarityAdvantage:2,bestMood:['Big vocals','Dramatic','Performance-driven'],friction:['Heavy interpersonal betrayal and emotionally loaded material'],gatewaySongs:[{song:'And I Am Telling You I’m Not Going',purpose:'maximum belt test'},{song:'One Night Only',purpose:'hook test'},{song:'Listen',purpose:'catharsis test'}],notes:'A vocal-performance engine with enormous emotional peaks, but the story material can make it context-sensitive.',provenance:[editorial('dreamgirls')]},
  lalaland:{format:'film',musicalType:'original',vocalStyle:['Light pop','Jazz-inflected','Intimate'],lyricalDensity:2.5,musicDrivenPercent:58,catharsis:4,rewatchability:3.8,familiarityAdvantage:1,bestMood:['Dreamy','Romantic','Bittersweet'],friction:['Lower belt density and more restrained propulsion than the engine’s strongest matches'],gatewaySongs:[{song:'Another Day of Sun',purpose:'propulsion test'},{song:'Someone in the Crowd',purpose:'movement test'},{song:'Audition (The Fools Who Dream)',purpose:'emotional test'}],notes:'Visually and musically elegant, but its lighter vocal attack and dreamlike pacing make it a useful contrast title.',provenance:[editorial('lalaland')]},
  colorpurple:{format:'film',musicalType:'adaptation',vocalStyle:['Gospel','Soul','Power belt','Ensemble'],lyricalDensity:3.5,musicDrivenPercent:70,catharsis:5,rewatchability:4.1,familiarityAdvantage:2,bestMood:['Ready for catharsis','Soulful','Emotionally sturdy'],friction:['Trauma-heavy story and intense emotional subject matter'],gatewaySongs:[{song:'Hell No!',purpose:'defiance and propulsion test'},{song:'Push Da Button',purpose:'movement and swagger test'},{song:"I'm Here",purpose:'full catharsis test'}],notes:'A deeply emotional gospel-and-soul musical whose payoff is enormous when the viewer has capacity for the story.',provenance:[editorial('colorpurple')]},
  encanto:{format:'animated',musicalType:'original',vocalStyle:['Contemporary musical theater','Pop ensemble','Character song'],lyricalDensity:4,musicDrivenPercent:68,catharsis:4.6,rewatchability:4.8,familiarityAdvantage:1,bestMood:['Comfort','Family feelings','Hooks'],friction:['Family-pressure themes can hit harder than the bright surface suggests'],gatewaySongs:[{song:'The Family Madrigal',purpose:'density and propulsion test'},{song:'Surface Pressure',purpose:'belt and emotional identification test'},{song:"We Don't Talk About Bruno",purpose:'ensemble hook test'}],notes:'Dense character writing and hooks disguised as family animation, with strong replay and comfort value.',provenance:[editorial('encanto')]},
  singstreet:{format:'film',musicalType:'original',vocalStyle:['80s pop-rock','New wave','Youthful rock'],lyricalDensity:2.5,musicDrivenPercent:62,catharsis:4.2,rewatchability:4.5,familiarityAdvantage:1,bestMood:['Creative spark','Hopeful','Band movie'],friction:['Less sung-through than a traditional musical'],gatewaySongs:[{song:'Drive It Like You Stole It',purpose:'propulsion and joy test'},{song:'Up',purpose:'melodic hook test'},{song:'Go Now',purpose:'emotional payoff test'}],notes:'Musical-adjacent in structure but highly propulsive when creativity and escape take over.',provenance:[editorial('singstreet')]},
  westside:{format:'film',musicalType:'adaptation',vocalStyle:['Classical musical theater','Legit belt','Ensemble'],lyricalDensity:3.5,musicDrivenPercent:75,catharsis:5,rewatchability:4.3,familiarityAdvantage:2,bestMood:['Big cinematic musical','Romantic tragedy','Movement'],friction:['Tragic ending and heavier dramatic material'],gatewaySongs:[{song:'America',purpose:'movement and ensemble test'},{song:'Tonight',purpose:'romantic lift test'},{song:'A Boy Like That / I Have a Love',purpose:'emotional intensity test'}],notes:'A full-scale cinematic musical with enormous movement and emotional amplitude despite a more traditional score profile.',provenance:[editorial('westside')]},
  littleShop:{format:'film',musicalType:'adaptation',vocalStyle:['Doo-wop','Pop-rock','Character belt'],lyricalDensity:3,musicDrivenPercent:76,catharsis:4,rewatchability:4.7,familiarityAdvantage:1,bestMood:['Camp','Dark comedy','Hooks'],friction:['Macabre humor and intentionally theatrical camp'],gatewaySongs:[{song:'Skid Row (Downtown)',purpose:'ensemble propulsion test'},{song:'Dentist!',purpose:'camp tolerance test'},{song:'Suddenly, Seymour',purpose:'belt and emotion test'}],notes:'Compact, hook-heavy, weird, and extremely singable. A valuable camp/maximalism anchor.',provenance:[editorial('littleShop')]},
  rocky:{format:'film',musicalType:'original',vocalStyle:['Glam rock','Camp theatrical','Rock ensemble'],lyricalDensity:2.5,musicDrivenPercent:72,catharsis:3.8,rewatchability:4.7,familiarityAdvantage:3,bestMood:['Camp','Party','Want weird'],friction:['Deliberately chaotic tone and dated transgressive humor'],gatewaySongs:[{song:'Time Warp',purpose:'movement and camp test'},{song:'Sweet Transvestite',purpose:'theatricality test'},{song:'Rose Tint My World',purpose:'late-film musical payoff test'}],notes:'Less emotional propulsion than some anchors, but exceptional communal singability, camp, and body-movement value.',provenance:[editorial('rocky')]},
  sweeney:{format:'film',musicalType:'adaptation',vocalStyle:['Dark musical theater','Character vocal','Operatic ensemble'],lyricalDensity:4.5,musicDrivenPercent:84,catharsis:4.5,rewatchability:4,familiarityAdvantage:2,bestMood:['Dark','Gothic','Dense score'],friction:['Bleak violence, low comfort, and deliberately grim atmosphere'],gatewaySongs:[{song:'The Ballad of Sweeney Todd',purpose:'density and gothic tone test'},{song:'A Little Priest',purpose:'lyrical wit test'},{song:'Johanna (Quartet)',purpose:'musical layering test'}],notes:'A dense, nearly continuous score with maximal narrative integration, but comfort is intentionally near zero.',provenance:[editorial('sweeney')]},
  lastfive:{format:'film',musicalType:'adaptation',vocalStyle:['Contemporary musical theater','Solo belt','Intimate'],lyricalDensity:4,musicDrivenPercent:90,catharsis:4.6,rewatchability:3.9,familiarityAdvantage:2,bestMood:['Relationship autopsy','Solo vocals','Bittersweet'],friction:['Emotionally bruising relationship structure and limited ensemble lift'],gatewaySongs:[{song:'Moving Too Fast',purpose:'propulsion test'},{song:'A Summer in Ohio',purpose:'comic hook test'},{song:'Still Hurting',purpose:'emotional intensity test'}],notes:'Almost entirely sung and emotionally direct. High narrative integration, lower communal/ensemble energy.',provenance:[editorial('lastfive')]}
};
let changed=0;
for(const x of data){if(P[x.id]){x.enrichment={...(x.enrichment||{}),...P[x.id]};changed++;}}
if(changed!==Object.keys(P).length) throw new Error(`Expected ${Object.keys(P).length} matches, got ${changed}`);
fs.writeFileSync(path,JSON.stringify(data,null,2)+'\n');
console.log(`Enriched ${changed} titles in batch 3`);
