import json
from pathlib import Path

p=Path('data/titles.json')
data=json.loads(p.read_text(encoding='utf-8'))
existing={x['id'] for x in data}

def t(id,title,year,runtime,rating,tag,vibe,dna,scores,why,risk,songs,links,fmt,mtype,vocal,lyrical,music,catharsis,rewatch,familiarity,moods,friction,gateways,notes):
    return {'id':id,'title':title,'year':year,'runtime':runtime,'rating':rating,'status':'unseen','tag':tag,'vibe':vibe,'dna':dna,'scores':scores,'why':why,'risk':risk,'songs':songs,'links':links,'enrichment':{'format':fmt,'musicalType':mtype,'vocalStyle':vocal,'lyricalDensity':lyrical,'musicDrivenPercent':music,'catharsis':catharsis,'rewatchability':rewatch,'familiarityAdvantage':familiarity,'bestMood':moods,'friction':friction,'gatewaySongs':[{'song':a,'purpose':b} for a,b in gateways],'notes':notes,'provenance':[{'type':'editorial-analysis','source':'Musical Propulsion Engine expansion batch 1','scope':'interpretive scoring and fit analysis'}]}}

new=[
t('spirited','Spirited',2022,'2h 7m','PG-13','Christmas maximalism with teeth',['Joyful','Feral','Comic','Earnest','Maximalist'],['Pop','Contemporary Musical Theater','Comedy','Holiday'],{'propulsion':4.7,'belt':4.8,'movement':5,'emotion':4.2,'comfort':4.2,'maximalism':5,'narrative':4.2,'hooks':4.6,'afterglow':4.5,'replay':4.6},'Huge choreography, aggressive commitment, comic escalation, and several songs built to become full-body events.','Holiday framing and broad comedy may be mood-dependent.',['Good Afternoon','Unredeemable','Do a Little Good','That Christmas Morning Feelin’'],['greatest','hairspray','kpop','prom'],'film','original',['pop belt','ensemble','comic patter','contemporary musical theater'],3,78,4.3,4.4,2,['high energy','holiday','movement','comic maximalism'],['holiday-specific setting','broad comedy'],[('Good Afternoon','comic escalation + ensemble propulsion'),('Unredeemable','belt payoff'),('Do a Little Good','emotional release')],'A strong maximalist test case where choreography and comic escalation do much of the propulsion work.'),
t('matilda','Matilda the Musical',2022,'1h 57m','PG','Rebellion has a beat',['Defiant','Whimsical','Dark','Triumphant','Cathartic'],['Musical Theater','Pop','Children’s Chorus','Dark Comedy'],{'propulsion':4.7,'belt':4.5,'movement':4.8,'emotion':4.7,'comfort':3.8,'maximalism':4.7,'narrative':5,'hooks':4.5,'afterglow':4.6,'replay':4.5},'Sharp lyrical storytelling, giant ensemble choreography, emotional cruelty-to-catharsis arcs, and a spectacular release valve in Revolting Children.','Its deliberately grotesque adults and child-abuse themes make the comfort level deceptive.',['Revolting Children','Naughty','School Song','When I Grow Up'],['annie','hairspray','encanto','prom'],'film','adaptation',['child ensemble','character belt','patter','contemporary musical theater'],4,82,4.8,4.5,2,['defiant','cathartic','clever lyrics','ensemble energy'],['dark treatment of children','grotesque comedy'],[('Revolting Children','maximum ensemble release'),('Naughty','character + lyrical hook'),('When I Grow Up','emotional afterglow')],'Excellent bridge between family-musical accessibility and surprisingly dark emotional architecture.'),
t('prom','The Prom',2020,'2h 10m','PG-13','Broadway glitter cannon',['Campy','Joyful','Earnest','Maximalist','Warm'],['Broadway','Pop','Dance','Comedy'],{'propulsion':4.4,'belt':4.8,'movement':4.8,'emotion':4.2,'comfort':4.4,'maximalism':5,'narrative':4,'hooks':4.3,'afterglow':4.4,'replay':4.2},'Unapologetically theatrical, belt-heavy, bright, campy, and built around large-scale musical release.','The celebrity satire and tonal broadness can feel synthetic.',['Tonight Belongs to You','Love Thy Neighbor','It’s Time to Dance','You Happened'],['hairspray','greatest','spirited','jamie'],'film','adaptation',['Broadway belt','pop musical theater','ensemble','dance'],3,76,4.3,4.2,2,['camp','bright','belt-along','comfort'],['broad tonal shifts','celebrity satire'],[('Tonight Belongs to You','ensemble maximalism'),('Love Thy Neighbor','dance propulsion'),('It’s Time to Dance','communal payoff')],'Useful high-maximalism title that tests whether sheer theatrical commitment can overcome tonal unevenness.'),
t('cyrano','Cyrano',2021,'2h 3m','PG-13','Yearning dressed in velvet',['Romantic','Yearning','Melancholic','Elegant','Devastating'],['Indie Rock','Orchestral','Musical Theater','Ballad'],{'propulsion':3.7,'belt':3.8,'movement':3.3,'emotion':5,'comfort':3.2,'maximalism':4.1,'narrative':4.8,'hooks':4,'afterglow':4.8,'replay':4},'Music functions as emotional confession, with aching repetition and a romantic-tragic arc that keeps tightening.','Lower movement and a deliberately mournful register make it a mood-specific recommendation.',['Someone to Say','Every Letter','Wherever I Fall','Madly'],['phantom','lastfive','once','westside'],'film','adaptation',['intimate vocal','indie rock','orchestral ballad','ensemble lament'],3,70,5,3.9,2,['yearning','romantic devastation','quiet catharsis'],['low movement','sustained melancholy'],[('Someone to Say','romantic yearning'),('Every Letter','narrative intimacy'),('Wherever I Fall','ensemble devastation')],'Expands the database toward restrained propulsion driven by yearning rather than spectacle.'),
t('wonka','Wonka',2023,'1h 56m','PG','Sugar-rush storybook musical',['Whimsical','Warm','Playful','Hopeful','Colorful'],['Pop','Orchestral','Classic Musical','Family'],{'propulsion':4.1,'belt':3.8,'movement':4.3,'emotion':3.8,'comfort':4.8,'maximalism':4.3,'narrative':4.3,'hooks':4.2,'afterglow':4.5,'replay':4.2},'Buoyant melody, storybook momentum, visual invention, and a comfort-forward tone with enough musical movement to stay airborne.','Lower emotional amplitude and belt intensity than the engine’s strongest anchors.',['A Hatful of Dreams','You’ve Never Had Chocolate Like This','For a Moment','Pure Imagination'],['moana','encanto','annie','matilda'],'film','original',['light tenor','ensemble','storybook musical theater','pop'],2,62,3.8,4.5,3,['comfort','whimsy','light movement','warm reset'],['lower belt intensity','gentler stakes'],[('A Hatful of Dreams','tone + melodic propulsion'),('You’ve Never Had Chocolate Like This','ensemble play'),('Pure Imagination','comfort payoff')],'A useful comfort-heavy benchmark where charm matters more than cathartic force.'),
t('meangirls','Mean Girls',2024,'1h 52m','PG-13','Pop claws, high-school chaos',['Glossy','Comic','Biting','Energetic','Campy'],['Pop','Contemporary Musical Theater','Dance','Comedy'],{'propulsion':4.4,'belt':4.6,'movement':4.7,'emotion':3.6,'comfort':3.5,'maximalism':4.5,'narrative':4.2,'hooks':4.4,'afterglow':4,'replay':4.3},'Modern pop production, sharp character songs, choreography, and a pace that rarely lets the musical energy fully drop.','Some adaptation choices flatten the stage score and emotional peaks.',['A Cautionary Tale','Sexy','Someone Gets Hurt','World Burn'],['hairspray','jamie','prom','kpop'],'film','adaptation',['pop belt','character vocal','ensemble','contemporary pop'],3,73,3.8,4.1,2,['camp','high energy','pop hooks','comic'],['glossy production can mute theatrical bite'],[('World Burn','belt + escalation'),('Sexy','comic hook density'),('Someone Gets Hurt','dark pop tension')],'Adds contemporary glossy pop-musical texture and a useful mid-emotion/high-movement profile.'),
t('newsies','Newsies: The Broadway Musical',2017,'2h 14m','PG','Athletic ensemble euphoria',['Triumphant','Defiant','Communal','Earnest','Electric'],['Broadway','Dance','Orchestral Pop','Ensemble'],{'propulsion':4.9,'belt':4.8,'movement':5,'emotion':4.4,'comfort':4.3,'maximalism':4.7,'narrative':4.8,'hooks':4.7,'afterglow':4.8,'replay':4.7},'Big ensemble vocals, athletic choreography, rally-song architecture, and constant communal forward motion.','Stage-capture presentation may feel less cinematic.',['Seize the Day','Santa Fe','The World Will Know','King of New York'],['hamilton','hairspray','heights','jcs'],'stage-capture','filmed-stage',['Broadway belt','male ensemble','orchestral pop','character ballad'],3,94,4.6,4.7,2,['defiant','movement','ensemble euphoria','belt-along'],['stage-capture visual language'],[('Seize the Day','ensemble propulsion'),('Santa Fe','yearning belt'),('The World Will Know','rally-song momentum')],'A high-value stage-capture addition with unusually strong movement and communal propulsion.'),
t('comefromaway','Come From Away',2021,'1h 46m','TV-14','Humanity at full velocity',['Humane','Funny','Urgent','Communal','Cathartic'],['Folk','Celtic','Musical Theater','Ensemble'],{'propulsion':4.8,'belt':4.2,'movement':4.2,'emotion':5,'comfort':4.4,'maximalism':3.8,'narrative':5,'hooks':4.4,'afterglow':5,'replay':4.6},'Near-continuous ensemble storytelling turns logistical chaos into rhythmic propulsion, then lands enormous communal catharsis.','Subject matter around 9/11 can make the emotional load heavier than the warmth suggests.',['Welcome to the Rock','Me and the Sky','Screech In','Somewhere in the Middle of Nowhere'],['hamilton','heights','newsies','once'],'stage-capture','filmed-stage',['ensemble storytelling','folk','Celtic','character belt'],5,96,5,4.7,1,['communal','humanity restored','cathartic','narrative momentum'],['9/11 context','emotionally intense real-world subject'],[('Welcome to the Rock','narrative propulsion'),('Me and the Sky','character catharsis'),('Screech In','communal release')],'Crucial evidence that maximalism is not required for extreme propulsion when ensemble narrative density is high.'),
t('shrek','Shrek the Musical',2013,'2h 10m','TV-PG','Fairytale camp with a giant heart',['Campy','Warm','Comic','Defiant','Earnest'],['Broadway','Comedy','Pop Rock','Family'],{'propulsion':4.2,'belt':4.6,'movement':4.2,'emotion':4.3,'comfort':4.4,'maximalism':4.5,'narrative':4.5,'hooks':4.3,'afterglow':4.4,'replay':4.2},'Broad comedy and theatrical excess hide a surprisingly sincere outsider story with strong belt moments and ensemble payoff.','Some humor is intentionally juvenile and the filmed-stage aesthetic is broad.',['Who I’d Be','I Know It’s Today','Freak Flag','Morning Person'],['jamie','hairspray','matilda','annie'],'stage-capture','filmed-stage',['Broadway belt','comic character vocal','ensemble','pop rock'],3,88,4.5,4.3,2,['camp','outsider anthem','comfort','belt-along'],['juvenile humor','broad theatricality'],[('Who I’d Be','yearning + belt payoff'),('Freak Flag','communal outsider anthem'),('I Know It’s Today','character storytelling')],'Adds camp-forward stage musical energy with genuine emotional payoff.'),
t('rockofages','Rock of Ages',2012,'2h 3m','PG-13','Hair-metal karaoke fever dream',['Feral','Campy','Sexy','Loud','Nostalgic'],['Jukebox','Hair Metal','Rock','Arena Rock'],{'propulsion':4.5,'belt':5,'movement':4.5,'emotion':3.4,'comfort':4,'maximalism':5,'narrative':3.2,'hooks':5,'afterglow':4.2,'replay':4.6},'Familiar arena-rock hooks, huge vocals, shameless mashups, and maximalist commitment make narrative subtlety almost irrelevant.','Thin story and deliberately trashy tone.',['Paradise City','Wanted Dead or Alive','Any Way You Want It','Don’t Stop Believin’'],['moulin','across','rocketman','hedwig'],'film','jukebox',['rock belt','arena vocal','ensemble mashup','power ballad'],2,80,3.5,4.5,5,['feral','karaoke','maximalist','rock belt'],['thin narrative','campy sexual humor'],[('Don’t Stop Believin’','communal belt payoff'),('Wanted Dead or Alive','rock vocal test'),('Any Way You Want It','jukebox propulsion')],'A useful stress test for how far hook familiarity and belt energy can carry a weak narrative.'),
t('purplerain','Purple Rain',1984,'1h 51m','R','Concert electricity as cinema',['Electric','Sensual','Brooding','Triumphant','Raw'],['Rock','Funk','Pop','R&B','Music Drama'],{'propulsion':4.3,'belt':4.6,'movement':4.7,'emotion':4.6,'comfort':3,'maximalism':4.5,'narrative':3.5,'hooks':5,'afterglow':5,'replay':5},'The performance sequences are overwhelming musical events, with hooks and charisma doing more propulsion work than the dramatic connective tissue.','The offstage relationship material is darker and rougher than the concert highs.',['Let’s Go Crazy','When Doves Cry','The Beautiful Ones','Purple Rain'],['walkline','rocketman','bohemian','hedwig'],'film','music-drama',['rock','funk falsetto','power ballad','live performance'],2,60,5,4.8,4,['concert high','raw emotion','hooks','movement'],['dated relationship dynamics','uneven dramatic passages'],[('Let’s Go Crazy','instant propulsion'),('The Beautiful Ones','vocal catharsis'),('Purple Rain','maximum afterglow')],'Expands the musical-adjacent category where performance sequences create the propulsion rather than integrated song dialogue.'),
t('hair','Hair',1979,'2h 1m','PG','Counterculture chorus in motion',['Freewheeling','Rebellious','Communal','Surreal','Bittersweet'],['Rock','Folk Rock','Counterculture','Ensemble'],{'propulsion':4.1,'belt':4.1,'movement':4.5,'emotion':4.2,'comfort':3.4,'maximalism':4.2,'narrative':3.8,'hooks':4.6,'afterglow':4.5,'replay':4.3},'Communal rock hooks, physical movement, and counterculture energy create a loose but infectious musical current.','Loose episodic structure and period politics may create distance.',['Aquarius','Hair','Easy to Be Hard','Let the Sunshine In'],['jcs','rocky','across','tommy'],'film','adaptation',['rock ensemble','folk rock','soul belt','choral'],2,72,4.4,4.2,4,['communal','rebellious','retro','movement'],['episodic narrative','period-specific framing'],[('Aquarius','immediate vibe lock'),('Hair','communal movement'),('Let the Sunshine In','cathartic finale')],'Adds a looser counterculture-rock form with high communal energy but less narrative integration.'),
t('tommy','Tommy',1975,'1h 51m','PG','Rock opera hallucination',['Surreal','Feral','Dark','Maximalist','Operatic'],['Rock Opera','Classic Rock','Psychedelic','Concept Album'],{'propulsion':4.6,'belt':4.5,'movement':4.3,'emotion':4.3,'comfort':2,'maximalism':5,'narrative':4.3,'hooks':4.8,'afterglow':4.6,'replay':4.3},'Almost continuous rock storytelling, iconic hooks, visual insanity, and total commitment to a concept-album universe.','Disturbing material, grotesque imagery, and aggressively strange filmmaking.',['Pinball Wizard','See Me, Feel Me','I’m Free','Acid Queen'],['jcs','rocky','hedwig','hair'],'film','rock-opera',['classic rock','power vocal','ensemble rock','operatic rock'],3,95,4.5,4.1,4,['weird','maximalist','rock opera','wild card'],['disturbing themes','grotesque imagery','extreme 1970s surrealism'],[('Pinball Wizard','hook + maximalism'),('See Me, Feel Me','rock catharsis'),('Acid Queen','feral vocal energy')],'A deliberate wild-card anchor for maximalism, rock-opera continuity, and high-strangeness tolerance.'),
t('blinded','Blinded by the Light',2019,'1h 58m','PG-13','Springsteen as emotional oxygen',['Yearning','Triumphant','Warm','Earnest','Nostalgic'],['Jukebox','Rock','Springsteen','Coming-of-Age'],{'propulsion':4,'belt':3.7,'movement':3.8,'emotion':4.7,'comfort':4.5,'maximalism':3.6,'narrative':4.5,'hooks':4.8,'afterglow':4.8,'replay':4.4},'Songs become identity language and emotional release, with familiar rock lyrics externalizing what the protagonist cannot yet say.','Less fully musical than the core catalog and more dependent on connection to Springsteen’s songs.',['Born to Run','Thunder Road','The Promised Land','Blinded by the Light'],['walkline','beginagain','singstreet','yesterday'],'film','jukebox',['rock playback','sing-along','dramatic song integration'],2,48,4.7,4.5,5,['yearning','coming of age','comfort','rock nostalgia'],['not a continuous musical','artist familiarity helps'],[('Born to Run','release + movement'),('Thunder Road','yearning'),('The Promised Land','identity propulsion')],'Useful musical-adjacent case where preexisting songs become explicit narrative and identity machinery.'),
t('yesterday','Yesterday',2019,'1h 56m','PG-13','Beatles hooks, romantic reset',['Warm','Romantic','Playful','Nostalgic','Bittersweet'],['Beatles','Jukebox','Pop Rock','Music Drama'],{'propulsion':3.7,'belt':3.4,'movement':3.4,'emotion':4,'comfort':4.6,'maximalism':3.1,'narrative':4,'hooks':5,'afterglow':4.4,'replay':4.3},'An absurdly strong songbook supplies instant hooks and comfort while the story uses musical recognition as its central emotional engine.','More rom-com with performances than integrated musical.',['Help!','Let It Be','Hey Jude','Yesterday'],['across','beginagain','blinded','singstreet'],'film','music-drama',['pop rock','acoustic','sing-along','performance vocal'],2,42,4,4.3,5,['comfort','Beatles','romantic','easy watch'],['low musical integration','gentle dramatic stakes'],[('Help!','performance propulsion'),('Let It Be','emotional familiarity'),('Hey Jude','communal hook payoff')],'Provides a low-integration/high-hook benchmark and a direct contrast with Across the Universe’s transformation of the same songbook.')
]

added=[]
for x in new:
    if x['id'] not in existing:
        data.append(x); existing.add(x['id']); added.append(x['id'])

p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Added {len(added)} titles: {", ".join(added)}')
if len(added) not in (0,15): raise RuntimeError(f'Unexpected partial expansion: {len(added)}')
