import json
from pathlib import Path
p=Path('data/titles.json'); data=json.loads(p.read_text()); existing={x['id'] for x in data}
def T(id,title,year,runtime,rating,tag,vibe,dna,s,why,risk,songs,links,fmt,typ,vocal,lyr,music,cat,re,fam,moods,friction,gateway,notes):
 return {'id':id,'title':title,'year':year,'runtime':runtime,'rating':rating,'status':'unseen','tag':tag,'vibe':vibe,'dna':dna,'scores':dict(zip(['propulsion','belt','movement','emotion','comfort','maximalism','narrative','hooks','afterglow','replay'],s)),'why':why,'risk':risk,'songs':songs,'links':links,'enrichment':{'format':fmt,'musicalType':typ,'vocalStyle':vocal,'lyricalDensity':lyr,'musicDrivenPercent':music,'catharsis':cat,'rewatchability':re,'familiarityAdvantage':fam,'bestMood':moods,'friction':friction,'gatewaySongs':[{'song':a,'purpose':b} for a,b in gateway],'notes':notes,'provenance':[{'type':'editorial-analysis','source':'Musical Propulsion Engine expansion batch 2','scope':'interpretive scoring and fit analysis'}]}}
new=[
T('chicago','Chicago',2002,'1h 53m','PG-13','Murder, jazz, razzle-dazzle',['Slick','Sexy','Cynical','Maximalist'],['Jazz','Vaudeville','Broadway'],[4.8,5,5,4.2,3.2,5,4.7,5,4.5,4.8],'A precision-engineered movie musical where choreography, editing, character psychology, and hooks all reinforce one another.','Cynicism keeps it cooler than the warmest comfort titles.',['Cell Block Tango','All That Jazz','Roxie'],['moulin','hairspray','dreamgirls'],'film','adaptation',['jazz belt','ensemble','vaudeville'],4,88,4.5,4.8,3,['maximalist','dance','darkly funny'],['cooler emotional temperature'],[('Cell Block Tango','ensemble bite'),('All That Jazz','instant style thesis')],'A foundational high-propulsion benchmark missing from the original catalog.'),
T('mammamia','Mamma Mia!',2008,'1h 48m','PG-13','ABBA sunshine cannon',['Joyful','Campy','Sunny','Romantic'],['Jukebox','Pop','ABBA'],[4.6,4.5,4.8,3.8,5,4.7,3.8,5,4.8,5],'Familiar hooks, communal singing, shameless joy, and almost no resistance to singing along.','Narrative integration is intentionally loose.',['Dancing Queen','Mamma Mia','The Winner Takes It All'],['moulin','hairspray','rockofages'],'film','jukebox',['pop','ensemble','character belt'],2,82,4.5,5,5,['comfort','sunshine','sing-along'],['loose narrative integration'],[('Dancing Queen','pure communal lift'),('The Winner Takes It All','emotional belt')],'Essential comfort-plus-hooks reference point.'),
T('soundmusic','The Sound of Music',1965,'2h 52m','G','Warmth with a spine',['Warm','Expansive','Tender','Triumphant'],['Golden Age','Orchestral','Folk'],[3.8,4,3.8,4.6,5,3.6,4.8,4.7,5,5],'An enduring comfort anchor with melodies that become emotional geography.','Long runtime and gentler propulsion.',['Do-Re-Mi','My Favorite Things','Climb Ev’ry Mountain'],['annie','westside','moana'],'film','adaptation',['legit','ensemble','orchestral'],2,70,4.8,5,5,['comfort','nostalgia','warmth'],['long runtime','gentle pacing'],[('My Favorite Things','comfort hook'),('Climb Ev’ry Mountain','cathartic payoff')],'Adds classic comfort without maximalist dependence.'),
T('grease','Grease',1978,'1h 50m','PG','Hooks in a leather jacket',['Playful','Nostalgic','Flirty','Energetic'],['Rock and Roll','Pop','Broadway'],[4.7,4.4,5,3.4,4.7,4.5,3.5,5,4.4,5],'An almost absurd concentration of recognizable hooks and movement energy.','Some character and gender dynamics have aged poorly.',['Summer Nights','Hopelessly Devoted to You','You’re the One That I Want'],['hairspray','mammamia','rockofages'],'film','adaptation',['pop','rock and roll','ensemble'],2,80,4,5,5,['sing-along','nostalgia','movement'],['dated gender dynamics'],[('You’re the One That I Want','duet propulsion'),('Summer Nights','ensemble hook density')],'Important familiarity-driven sing-along benchmark.'),
T('burlesque','Burlesque',2010,'1h 59m','PG-13','Vocals first, subtlety never',['Glossy','Sexy','Belty','Campy'],['Pop','Burlesque','Dance'],[4.5,5,4.8,3.5,3.8,5,3.2,4.8,4.2,4.6],'Big voices, stage spectacle, dance, and unapologetic performance energy.','Story exists mostly to move between numbers.',['Show Me How You Burlesque','Bound to You','Express'],['moulin','chicago','dreamgirls'],'film','original',['power belt','pop','diva vocal'],2,72,4.1,4.5,3,['belt-along','glamour','performance'],['thin narrative'],[('Show Me How You Burlesque','maximum stage energy'),('Bound to You','vocal catharsis')],'Useful test of whether vocal spectacle can outweigh narrative weakness.'),
T('pitchperfect','Pitch Perfect',2012,'1h 52m','PG-13','Competitive harmony dopamine',['Funny','Hooky','Competitive','Communal'],['A cappella','Pop','Mashup'],[4.6,4.5,4.8,3.4,4.6,4.2,3.5,5,4.5,5],'Mashups, recognizable pop, ensemble chemistry, and performance stakes create musical propulsion without traditional musical storytelling.','Songs are performances rather than narrative speech.',['Cups','Bellas Finals','Riff Off'],['kpop','sister2','mammamia'],'film','music-performance',['a cappella','pop','ensemble'],2,62,3.8,5,5,['funny','communal','easy replay'],['not a traditional musical'],[('Bellas Finals','mashup payoff'),('Riff Off','competitive propulsion')],'Expands musical-adjacent performance territory.'),
T('coco','Coco',2017,'1h 45m','PG','Family memory detonator',['Warm','Colorful','Tender','Cathartic'],['Mexican Folk','Pop','Animation'],[4.2,4,4.1,5,5,4.2,5,4.6,5,5],'Music is literally the mechanism of memory, family, identity, and emotional release.','Less belt-driven than the strongest anchors.',['Remember Me','Un Poco Loco','Proud Corazón'],['moana','encanto','kpop'],'animated','original',['folk-pop','character vocal','ensemble'],3,62,5,5,2,['comfort','family','crying in a good way'],['lower belt intensity'],[('Remember Me','emotional architecture'),('Un Poco Loco','movement and play')],'Strengthens animation as a serious emotional-musical category.'),
T('princessfrog','The Princess and the Frog',2009,'1h 37m','G','New Orleans groove + yearning',['Warm','Playful','Romantic','Driven'],['Jazz','Gospel','Disney'],[4.4,4.5,4.7,4.4,4.7,4.2,4.8,4.7,4.7,4.8],'A compact Disney musical with unusually strong rhythmic identity, aspiration songs, and gospel release.','Smaller-scale spectacle than newer animation.',['Almost There','Friends on the Other Side','Dig a Little Deeper'],['moana','encanto','sister2'],'animated','original',['jazz','gospel','character belt'],3,68,4.6,4.8,2,['comfort','groove','yearning'],['less maximalist'],[('Almost There','aspiration belt'),('Dig a Little Deeper','gospel lift')],'Adds jazz and gospel texture to animation coverage.'),
T('tangled','Tangled',2010,'1h 40m','PG','Yearning with lanterns',['Romantic','Warm','Funny','Yearning'],['Disney','Pop','Orchestral'],[4.3,4.6,4.2,4.7,5,4.1,4.8,4.8,5,5],'Strong yearning songs, romantic payoff, comedy, and unusually high comfort rewatchability.','Not relentlessly musical.',['When Will My Life Begin?','I See the Light','Mother Knows Best'],['moana','encanto','annie'],'animated','original',['pop belt','duet','character song'],3,64,4.8,5,2,['comfort','romance','yearning'],['music occupies less runtime'],[('When Will My Life Begin?','yearning propulsion'),('I See the Light','romantic payoff')],'Adds a high-comfort Disney reference with moderate musical density.'),
T('frozen','Frozen',2013,'1h 42m','PG','The belt heard around the world',['Triumphant','Warm','Funny','Emotional'],['Disney','Pop','Broadway'],[4.5,5,4.4,4.6,4.8,4.6,4.8,5,4.8,5],'Huge hooks and clear emotional song functions make the soundtrack almost frictionless.','Cultural overexposure may reduce novelty.',['Let It Go','For the First Time in Forever','Love Is an Open Door'],['moana','encanto','tangled'],'animated','original',['power belt','pop','duet'],3,70,4.7,5,5,['belt-along','comfort','big hooks'],['possible overfamiliarity'],[('Let It Go','maximum belt release'),('For the First Time in Forever','narrative duet propulsion')],'Useful extreme case for familiarity plus hook density.'),
T('waitress','Waitress',2023,'2h 24m','Not Rated','Pie, yearning, Sara Bareilles',['Tender','Funny','Yearning','Cathartic'],['Pop','Singer-Songwriter','Broadway'],[4.1,4.8,3.5,5,4.2,3.6,5,4.8,5,4.8],'Emotionally legible songwriting with enormous vocal payoff and intimate narrative integration.','Stage capture and quieter pacing reduce visual propulsion.',['She Used to Be Mine','Opening Up','What Baking Can Do'],['lastfive','ticktick','once'],'stage-capture','filmed-stage',['pop belt','singer-songwriter','ensemble'],4,90,5,4.8,2,['yearning','catharsis','lyrics'],['quieter staging'],[('She Used to Be Mine','devastating belt payoff'),('Opening Up','ensemble momentum')],'Fills the contemporary stage-capture singer-songwriter gap.'),
T('legallyblonde','Legally Blonde: The Musical',2007,'2h 2m','TV-PG','Pink, precise, propulsive',['Joyful','Belty','Funny','Triumphant'],['Pop','Broadway','Dance'],[5,5,5,4.3,4.6,4.8,5,5,4.8,5],'A relentless contemporary musical-theater machine with hooks, choreography, comedy, and escalating character payoff.','Stage capture aesthetics rather than cinematic polish.',['So Much Better','Omigod You Guys','Legally Blonde Remix'],['hairspray','meanGirls','newsies'],'stage-capture','filmed-stage',['pop belt','ensemble','comedy patter'],4,96,4.8,5,2,['high energy','belt-along','confidence'],['stage capture visuals'],[('So Much Better','pure belt propulsion'),('Legally Blonde Remix','late-show escalation')],'Likely high-value unseen title because it hits nearly every core dimension.'),
T('falsettos','Falsettos',2017,'2h 24m','TV-14','Neurosis becomes harmony',['Witty','Intimate','Devastating','Dense'],['Broadway','Sung-through','Chamber Pop'],[4.1,4.4,3.3,5,2.8,3.5,5,4.4,5,4.4],'Dense character writing and musical callbacks accumulate into severe emotional payoff.','Low comfort and less body-movement energy.',['Four Jews in a Room Bitching','I’m Breaking Down','What Would I Do?'],['lastfive','rent','deh'],'stage-capture','filmed-stage',['ensemble','character belt','patter'],5,98,5,4.3,2,['lyric hungry','emotionally brave','character study'],['low comfort','devastating ending'],[('I’m Breaking Down','comic vocal escalation'),('What Would I Do?','emotional payoff')],'Adds high-density intimate stage storytelling.'),
T('marypoppins','Mary Poppins Returns',2018,'2h 10m','PG','Old-school craft, modern polish',['Whimsical','Warm','Theatrical','Comforting'],['Disney','Golden Age Revival','Orchestral'],[3.9,4.2,4.4,4.1,4.8,4.3,4.5,4.2,4.4,4.2],'Traditional musical craft with elaborate production numbers and warm family stakes.','Songs are less instantly sticky than the strongest Disney anchors.',['Trip a Little Light Fantastic','A Cover Is Not the Book','The Place Where Lost Things Go'],['annie','soundmusic','moana'],'film','original',['legit','ensemble','character vocal'],3,68,4.3,4.2,2,['comfort','whimsy','family'],['lower hook density'],[('Trip a Little Light Fantastic','production-number propulsion'),('The Place Where Lost Things Go','tender emotional core')],'Adds polished traditional-family-musical coverage.'),
T('starsborn','A Star Is Born',2018,'2h 16m','R','Performance becomes heartbreak',['Romantic','Raw','Tragic','Cathartic'],['Pop','Rock','Music Drama'],[3.8,5,3.4,5,2.7,3.8,4.7,5,5,4.6],'Not a traditional musical, but songs carry identity, intimacy, fame, and devastating emotional payoff.','Heavy subject matter and long dramatic stretches between songs.',['Shallow','Always Remember Us This Way','I’ll Never Love Again'],['walkline','beginagain','rocketman'],'film','music-drama',['power belt','rock','pop ballad'],2,48,5,4.5,4,['cry','belt','romantic tragedy'],['heavy themes','lower music density'],[('Shallow','performance-to-intimacy bridge'),('I’ll Never Love Again','maximum catharsis')],'Expands the music-drama boundary with very high vocal and emotional amplitude.')]
for x in new:
 if x['id'] not in existing:data.append(x)
assert len({x['id'] for x in data})==len(data)
p.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
print('catalog',len(data),'added',sum(x['id'] not in existing for x in new))
